### ISSUE TITLE
unplayable on unciv v 4.1.13 patch 2

### ISSUE THREAD

**Issue by uwumonarch** [yairm210/Civ-IV#17]
Longbowman's unique "[+25]% Strength <when fighting in [City center] tiles> <when defending>" contains the conditional "when fighting in [City center] tiles". This contains the parameter City center which does not fit parameter type tileFilter !
Supermarket's unique "[+1 Food] from [Cow] tiles [in this city]" contains parameter Cow, which does not fit parameter type tileFilter !
Supermarket's unique "[+1 Food] from [Deer] tiles [in this city]" contains parameter Deer, which does not fit parameter type tileFilter !
Supermarket's unique "[+1 Food] from [Sheep] tiles [in this city]" contains parameter Sheep, which does not fit parameter type tileFilter !
Supermarket's unique "[+1 Food] from [Pig] tiles [in this city]" contains parameter Pig, which does not fit parameter type tileFilter !
reveal nearby Barbarian camps's unique "Reveal up to [All] [Barbarian encampment] within a [10] tile radius" contains parameter Barbarian encampment, which does not fit parameter type tileFilter !
Guerrilla I's unique "[+20]% Strength <when fighting in [Hills] tiles> <when defending>" contains the conditional "when fighting in [Hills] tiles". This contains the parameter Hills which does not fit parameter type tileFilter !
Road has an empty `terrainsCanBeBuiltOn`, isn't allowed to only improve resources and isn't unbuildable! Support for this will soon end. Either give this the unique "Unbuildable", "Can only be built to improve a resource" or add "Land", "Water" or any other value to `terrainsCanBeBuiltOn`.
Railroad has an empty `terrainsCanBeBuiltOn`, isn't allowed to only improve resources and isn't unbuildable! Support for this will soon end. Either give this the unique "Unbuildable", "Can only be built to improve a resource" or add "Land", "Water" or any other value to `terrainsCanBeBuiltOn`.
Camp has an empty `terrainsCanBeBuiltOn`, isn't allowed to only improve resources and isn't unbuildable! Support for this will soon end. Either give this the unique "Unbuildable", "Can only be built to improve a resource" or add "Land", "Water" or any other value to `terrainsCanBeBuiltOn`.
Pasture has an empty `terrainsCanBeBuiltOn`, isn't allowed to only improve resources and isn't unbuildable! Support for this will soon end. Either give this the unique "Unbuildable", "Can only be built to improve a resource" or add "Land", "Water" or any other value to `terrainsCanBeBuiltOn`.
Quarry has an empty `terrainsCanBeBuiltOn`, isn't allowed to only improve resources and isn't unbuildable! Support for this will soon end. Either give this the unique "Unbuildable", "Can only be built to improve a resource" or add "Land", "Water" or any other value to `terrainsCanBeBuiltOn`.
Workshop has an empty `terrainsCanBeBuiltOn`, isn't allowed to only improve resources and isn't unbuildable! Support for this will soon end. Either give this the unique "Unbuildable", "Can only be built to improve a resource" or add "Land", "Water" or any other value to `terrainsCanBeBuiltOn`.
Winery has an empty `terrainsCanBeBuiltOn`, isn't allowed to only improve resources and isn't unbuildable! Support for this will soon end. Either give this the unique "Unbuildable", "Can only be built to improve a resource" or add "Land", "Water" or any other value to `terrainsCanBeBuiltOn`.
Plantation has an empty `terrainsCanBeBuiltOn`, isn't allowed to only improve resources and isn't unbuildable! Support for this will soon end. Either give this the unique "Unbuildable", "Can only be built to improve a resource" or add "Land", "Water" or any other value to `terrainsCanBeBuiltOn`.
Victory type Scientific requires adding the non-existant unit SS Engine to the capital to win!
Victory type Scientific requires adding the non-existant unit SS Stasis Chamber to the capital to win!
Victory type Scientific requires adding the non-existant unit SS Cockpit to the capital to win!
Victory type Scientific requires adding the non-existant unit SS Booster to the capital to win!
Victory type Scientific requires adding the non-existant unit SS Booster to the capital to win!
Victory type Scientific requires adding the non-existant unit SS Booster to the capital to win!
Ironclad's unique "Requires [1] [Coal]" looks like it may be a misspelling of:
	"Requires [buildingName/tech/era/policy]" (Deprecated)
Ironclad's unique "Requires [1] [Iron]" looks like it may be a misspelling of:
	"Requires [buildingName/tech/era/policy]" (Deprecated)
Modern Armor's unique "Requires [1] [Aluminum]" looks like it may be a misspelling of:
	"Requires [buildingName/tech/era/policy]" (Deprecated)
Modern Armor's unique "Requires [1] [Oil]" looks like it may be a misspelling of:
	"Requires [buildingName/tech/era/policy]" (Deprecated)
Jet Fighter's unique "Requires [1] [Aluminum]" looks like it may be a misspelling of:
	"Requires [buildingName/tech/era/policy]" (Deprecated)
Jet Fighter's unique "Requires [1] [Oil]" looks like it may be a misspelling of:
	"Requires [buildingName/tech/era/policy]" (Deprecated)
Stealth Bomber's unique "Requires [1] [Aluminum]" looks like it may be a misspelling of:
	"Requires [buildingName/tech/era/policy]" (Deprecated)
Stealth Bomber's unique "Requires [1] [Oil]" looks like it may be a misspelling of:
	"Requires [buildingName/tech/era/policy]" (Deprecated)
Ironclad's unique "Requires [1] [Coal]" looks like it may be a misspelling of:
	"Requires [buildingName/tech/era/policy]" (Deprecated)
Ironclad's unique "Requires [1] [Iron]" looks like it may be a misspelling of:
	"Requires [buildingName/tech/era/policy]" (Deprecated)
Modern Armor's unique "Requires [1] [Aluminum]" looks like it may be a misspelling of:
	"Requires [buildingName/tech/era/policy]" (Deprecated)
Modern Armor's unique "Requires [1] [Oil]" looks like it may be a misspelling of:
	"Requires [buildingName/tech/era/policy]" (Deprecated)
Jet Fighter's unique "Requires [1] [Aluminum]" looks like it may be a misspelling of:
	"Requires [buildingName/tech/era/policy]" (Deprecated)
Jet Fighter's unique "Requires [1] [Oil]" looks like it may be a misspelling of:
	"Requires [buildingName/tech/era/policy]" (Deprecated)
Stealth Bomber's unique "Requires [1] [Aluminum]" looks like it may be a misspelling of:
	"Requires [buildingName/tech/era/policy]" (Deprecated)
Stealth Bomber's unique "Requires [1] [Oil]" looks like it may be a misspelling of:
	"Requires [buildingName/tech/era/policy]" (Deprecated)

**Comment by tsunamistate** [comment]
Still happens on v4.2.18 (build 762)

**Comment by chross** [comment]
I can confirm this exact error

**Comment by yairm210** [comment]
Solved
