### ISSUE TITLE
Mod Name: `Civ IV`

### ISSUE THREAD

**Issue by RobLoach** [yairm210/Civ-IV#38]
Have the name of the mod be `Civ IV` to match the the other `Civ V` ruleset.

![Screenshot from 2024-10-10 23-08-21](https://github.com/user-attachments/assets/5d3aa2b6-d5e3-484c-8232-33cf3597b6ca)

Potentially...
- Rename the repo to `Civ IV`
- Have some method for the "internal mod name that differs from repo name"

**Comment by yairm210** [comment]
Done
