### ISSUE TITLE
Ships cannot go to ocean tiles with Optics

### ISSUE THREAD

**Issue by Kzer-Za** [yairm210/Civ-IV#79]
Game version: 4.14.9.
Mod info: updated 2024-11-25.
OS: Android.

As far as I know, ships should be able to go into ocean tiles after discovering Optics. Currently they are able to do it only after Astronomy.

Prerequisites:

1. Have Optics researched, but Astronomy not researched yet.
2. Have a naval unit built and located on a coast tile.

Steps to reproduce:

1. Select the naval unit.
2. Click on an ocean tile

The expected result: the ship should go to the clicked ocean tile.

The actual result: ship does not go to the clicked ocean tile.

Further steps:

3. Research Astronomy.
4. Select the same naval unit and click on the ocean tile.

The actual (and expected) result: the ship goes to the clicked ocean tile.

**Comment by RobLoach** [comment]
Thanks for the report! Know if this is different in Beyond the Sword?
