### ISSUE TITLE
Steam Power adds +50% to construction time of all the tile improvements.

### ISSUE THREAD

**Issue by Kzer-Za** [yairm210/Civ-IV#83]
Game version: 4.14.9.
Mod info: updated 2024-11-25.
OS: Android.

Steam Power *adds* 50% to construction time of all the tile improvements instead of subtracting it. Thus, after researching it, all the tile improvements take 50% more time to construct.

Prerequisites:

1. Have Steam power almost researched, so that only 1 turn remains to completion.
2. Have several worker units positioned on several tiles that need different improvements.

Steps to reproduce:

1. Give the worker units orders to construct these improvements
2. Write down how many turns each improvement takes.
3. Cancel construction orders.
4. Press Next turn.
5. Again give these worker units orders to construct the same improvements.

The expected result: the construction times should be 1/2 of the previous values.

The actual result: the construction times are approximately 1.5 of the previous values.

**Comment by RobLoach** [comment]
Thanks for catching this. Definitely a mistake on my part. Fixed!
