### ISSUE TITLE
Forts can't be built in neutral territory

### ISSUE THREAD

**Issue by Kzer-Za** [yairm210/Civ-IV#86]
Game version: 4.14.9.
Mod info: updated 2024-11-25.
OS: Android.

According to this https://civilization.fandom.com/wiki/Fort_(Civ4) you should be able to build forts in neutral territory. However, you can build them only within your culture borders. This greatly lowers the usefulness of forts.

Prerequisites:

1. Have Mathematics researched.
2. Have a worker positioned outside yours and any other civilization's cultural borders.

Steps to reproduce:

1. Select the worker.
2. Select "Construct improvement" menu item.

The actual result: "Fort" menu item is grayed out and has an instruction "Have this tile inside your empire" on its right.

The expected result: "Fort" menu item should be selectable.

**Comment by RobLoach** [comment]
Added a fix
 Mind testing?

**Comment by Kzer-Za** [comment]
Just tested it, everything is fine! Thanks!

**Comment by RobLoach** [comment]
Thanks so much for the help, and catching that.
