### ISSUE TITLE
Dikes can be built only in cities located on rivers AND coast

### ISSUE THREAD

**Issue by Kzer-Za** [yairm210/Civ-IV#91]
According to this (https://civilization.fandom.com/wiki/Dike_(Civ4)), dikes can be built in coastal and riverside cities, and this forum thread (https://forums.civfanatics.com/threads/levee-dike-city-location-requirements.330172/) explains it as a city built _either_ on a river _or_ on a coast (and in fact, adjacent to a lake tile works too).

However, in Unciv with Civ IV ruleset, when playing as Netherlands, a city can build a dike only if it is both on a coast AND on a river tile.

Game version: 4.14.11
Mod info: updated 2024-12-09
OS: Android

Prerequisites (I suggest starting a game in Modern era, so that you start with Steam Power researched and with 3 Settler units):
1. Play as Netherlands.
2. Have Steam Power researched.
3. Have 3 cities built: one simply on a coast (without a river adjacent), one simply on a river (without being on a coast), and one both on a river and on a coast.

Steps to reproduce:
1. Select each of these cities, one by one, and go into their City screen.
2. Scroll down to the building list and look for Dike menu item.

The expected result: all 3 cities should have Dike available.

The actual result: only the third city (both on a coast and adjacent to a river) has Dike in the list of available buildings.

**Comment by RobLoach** [comment]
Good catch! I don't think I knew the logic for this condition originally. Did some testing and now it should be working. Thanks!
